#!/bin/bash

# kill subprocesses on exit or kill
trap '[ -n "$(jobs -pr)" ] && kill -9 $(jobs -pr)' SIGINT SIGTERM EXIT

stainless-dotty --config-file=stainless.conf common.scala encoder.scala decoder.scala -J-Xms10G -J-Xss20M "$@"